<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
دست‌گرمی
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این تمرین می‌خواهیم مقدمات کار با <code>numpy</code> را با هم تمرین کنیم.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سوال ۱
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در سوال ۱ قصد داریم نسبت به سرعت بالای آرایه‌های 
<code>numpy</code>
 در مقایسه با لیست‌های پایتون در محاسبات عددی شهود بهتری پیدا کنیم.
 بدین منظور از شما می‌خواهیم به دو روش تابع محاسبه نرم اقلیدسی (نرم ۲) را بنویسید. این تابع  لیستی از اعداد را (که نمایانگر یک بردار است) به عنوان ورودی گرفته و نرم 
 اقلیدسی آن را به خروجی می‌دهد. فرمول محاسبه نرم اقلیدسی بردار
 <code>X</code>
در ادامه آمده است.
</font>
</p>

$$
\|\mathbf{X}\|_2 = \sqrt{\sum_{i=1}^n x_i^2}
$$


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<b style="color:#0099cc">توضیح فرمول:</b>
نخست هر عنصر لیست را به توان ۲ رسانده، سپس این مقادیر را با همدیگر جمع کرده و نهایتاً از آن‌ جذر بگیرید.
</p>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
 در حالت اول تابعی تحت عنوان <code>euclidean_norm_list</code> بنویسید. این تابع را بدون استفاده از پکیج </font>
<code>numpy</code>
و تنها با توابع و متد‌های لیست پایتون پیاده‌سازی کنید. می‌توانید در صورت نیاز از ماژول <code>math</code>
استفاده کنید.
</p>

In [9]:
def euclidean_norm_list(mylist):
    import math
    py_list = [num ** 2 for num in mylist]
    norm_2 = math.sqrt(sum(py_list))
    return norm_2


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
اکنون تابعی با نام 
<code>euclidean_norm_np</code>
بنویسید تا نرم اقلیدسی را با استفاده از پکیج <code>numpy</code>
محاسبه کند.
</p>

In [8]:
def euclidean_norm_np(mylist):
    import numpy as np
    power_func = lambda x: x**2
    np_array = np.array(mylist)
    np_array = power_func(np_array)
    norm_2 = np.sqrt(np.sum(np_array))
    return norm_2

In [7]:
euclidean_norm_np([2, 3, 4])

np.float64(5.385164807134504)


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
جهت مقایسه سرعت اجرای دو تابع، از دستور جادویی 
<code>timeit</code>    
 و برای ذخیره نتایج در متغیر‌های <code>a</code> و <code>b</code> از آرگومان 
<code dir=ltr>-o</code>
استفاده خواهیم کرد. 
جهت کسب اطلاعات بیشتر درباره‌ی <i>دستورات جادویی (magic codes)</i> می‌توانید به این
<a href="https://coderzcolumn.com/tutorials/python/list-of-useful-magic-commands-in-jupyter-notebook-lab"> لینک</a>
مراجعه کنید.
لیست اعداد ورودی برای تست توابع و دستورات
<code>timeit</code> 
در ادامه آمده است، تنها لازم است پس از تکمیل توابع فوق قطعه کد‌های زیر را اجرا نمایید تا مدت زمان اجرای هر تابع را در خروجی دریافت کنید. 
</p>

In [10]:
input = list(range(1000000))

In [11]:
a = %timeit -o euclidean_norm_list(input)

175 ms ± 9.86 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
b = %timeit -o euclidean_norm_np(input)

81.1 ms ± 12.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
با استفاده از دستور جادویی <code>save</code> کد تابع خود را در قالب فایل <code dir=ltr>.py</code> ذخیره کنید تا بتوانیم در سلول جواب‌ساز، آن را در فایل <code>result.zip</code> قرار دهیم.
</font>
</p>


In [ ]:
from inspect import getsource
%save euclidean_norm_list getsource(euclidean_norm_list)
%save euclidean_norm_np getsource(euclidean_norm_np)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سوال ۲
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این بخش از شما می‌خواهیم تابعی به نام <code>custom_filter</code>
 با دو ورودی 
<code>arr</code>
و
<code>L</code>
بنویسید که
<code>arr</code>
یک آرایه‌ی دو بعدی متشکل از آرایه‌های تک بعدی با طول 
<code>n</code>
است و 
<code>L</code>
لیستی به طول 
<code>n</code> باشد.
عملکرد تابع 
<code>custom_filter</code>
به این‌صورت است که نخست <code>L</code> را به انتهای آرایه <code>arr</code> اضافه‌ می‌کند (منظور <code>append</code> است)، سپس در آرایه‌ی دو بعدی جدید، هر ستونی (آرایه‌ی دوبعدی را همچون یک ماتریس در نظر بگیرید) را که شامل عددی بزرگتر مساوی ۱۰ یا کوچکتر مساوی ۱ است از آرایه حذف می‌کند و نهایتاً آرایه را به خروجی تابع می‌دهد. چنان‌چه آرایه‌ی خروجی تهی باشد به جای آن عبارت <code>Null</code> به صورت <code>string</code> در خروجی نمایش داده می‌شود. 
</font>
</p>

In [41]:
def custom_filter(arr,L):
    import numpy as np
    L = np.array([L])
    new_arr = np.append(arr, L, axis=0)
    result = []
    for row in new_arr.T:
        for element in row:
            if element <= 1 or element >= 10:
                break    
        else:
            result.append(row)
    if result:
        return np.array(result).T
    else:
        return "NULL"

In [42]:
import numpy as np
custom_filter(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), [8, 9, 10])

array([[2],
       [5],
       [8],
       [9]])

In [43]:
custom_filter(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), [7, 8, 9])

array([[2, 3],
       [5, 6],
       [8, 9],
       [8, 9]])

In [44]:
custom_filter(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), [9, 10, 11])

'NULL'


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<b style="color:purple">توجه:</b>
نمونه‌هایی از ورودی و خروجی تابع به صورت کامنت در سلول زیر قرار داده شده است. 
</font>
</p>

In [8]:
###################################################################################
#Ex1: custom_filter(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),[8,9,10])
# array([[2],
#        [5],
#        [8],
#        [9]])

#Ex2: custom_filter(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),[7,8,9])
# array([[2, 3],
#        [5, 6],
#        [8, 9],
#        [8, 9]])

#Ex3: custom_filter(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),[9,10,11])
#'Null'
###################################################################################

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
با استفاده از دستور جادویی <code>save</code> کد تابع خود را در قالب فایل <code dir=ltr>.py</code> ذخیره کنید تا بتوانیم در سلول جواب‌ساز، آن را در فایل <code>result.zip</code> قرار دهیم.
</font>
</p>


In [ ]:
from inspect import getsource
%save custom_filter getsource(custom_filter)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zlib
import zipfile
import joblib

joblib.dump(a,"a")
joblib.dump(b,"b")

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ['euclidean_norm_list.py', 'euclidean_norm_np.py',
              'custom_filter.py', 'a', 'b', 'warm_up.ipynb']

compress(file_names)